// Generated by CoffeeScript 1.6.3
(function() {
  var BAP, TRM, TYPES, alert, badge, debug, echo, help, info, log, njs_fs, njs_util, rpr, warn, whisper;

  njs_util = require('util');

  njs_fs = require('fs');

  BAP = require('coffeenode-bitsnpieces');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'scratch';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  this.page_and_line_nr = function(page_nr, line_nr) {
    page_nr = parseInt(page_nr, 10);
    line_nr = parseInt(line_nr, 10);
    echo("helo from NodeJS.");
    return echo("this paragraph appears on page " + page_nr + ", column ..., line " + line_nr + ".");
  };

  this.main = function() {
    var command, message, method_name, parameter, parameters;
    command = process.argv[2];
    parameter = process.argv[3];
    parameters = parameter.split(',');
    method_name = command.replace(/-/g, '_');
    echo("!!! DEBUG command: " + (rpr(command)) + ", parameter: " + (rpr(parameter)) + ". !!!");
    if (this[method_name] == null) {
      message = "!!! Unknown command: " + (rpr(command)) + " !!!";
      log(message);
      echo(message);
      return null;
    }
    return this[method_name].apply(this, parameters);
  };

  this.main();

}).call(this);
